#!/bin/bash
duration=$(( SECONDS - start ))
echo "Congratulations, YOU WIN!!!"
#echo "Your time is: $duration seconds"
echo "time duration: $duration" >> /home/gaben/.challenger
echo "----------------------------------------" >> /home/gaben/.challenger

